

=== Analysis for 12H Timeframe ===
Error in prepare_data: Error tokenizing data. C error: Calling read(nbytes) on source failed. Try engine='python'.
Traceback (most recent call last):
  File "/Users/spencerduran/Code_Repos/quant-futures-analytics-py/TheStrat/sss50_percent_stats/sss50_percent_stats.py", line 15, in prepare_data
    self.df = pd.read_csv(filepath)
  File "/Users/spencerduran/.pyenv/versions/3.10.8/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/spencerduran/.pyenv/versions/3.10.8/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 626, in _read
    return parser.read(nrows)
  File "/Users/spencerduran/.pyenv/versions/3.10.8/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1923, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
  File "/Users/spencerduran/.pyenv/versions/3.10.8/lib/python3.10/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
  File "parsers.pyx", line 838, in pandas._libs.parsers.TextReader.read_low_memory
  File "parsers.pyx", line 905, in pandas._libs.parsers.TextReader._read_rows
  File "parsers.pyx", line 874, in pandas._libs.parsers.TextReader._tokenize_rows
  File "parsers.pyx", line 891, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "parsers.pyx", line 2061, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Calling read(nbytes) on source failed. Try engine='python'.

Error in prepare_data: Error tokenizing data. C error: Calling read(nbytes) on source failed. Try engine='python'.
Traceback (most recent call last):
  File "/Users/spencerduran/Code_Repos/quant-futures-analytics-py/TheStrat/sss50_percent_stats/sss50_percent_stats.py", line 15, in prepare_data
    self.df = pd.read_csv(filepath)
  File "/Users/spencerduran/.pyenv/versions/3.10.8/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/spencerduran/.pyenv/versions/3.10.8/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 626, in _read
    return parser.read(nrows)
  File "/Users/spencerduran/.pyenv/versions/3.10.8/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1923, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
  File "/Users/spencerduran/.pyenv/versions/3.10.8/lib/python3.10/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
  File "parsers.pyx", line 838, in pandas._libs.parsers.TextReader.read_low_memory
  File "parsers.pyx", line 905, in pandas._libs.parsers.TextReader._read_rows
  File "parsers.pyx", line 874, in pandas._libs.parsers.TextReader._tokenize_rows
  File "parsers.pyx", line 891, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "parsers.pyx", line 2061, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Calling read(nbytes) on source failed. Try engine='python'.



=== Analysis for 4H Timeframe ===
Error in prepare_data: Error tokenizing data. C error: Calling read(nbytes) on source failed. Try engine='python'.
Traceback (most recent call last):
  File "/Users/spencerduran/Code_Repos/quant-futures-analytics-py/TheStrat/sss50_percent_stats/sss50_percent_stats.py", line 15, in prepare_data
    self.df = pd.read_csv(filepath)
  File "/Users/spencerduran/.pyenv/versions/3.10.8/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/spencerduran/.pyenv/versions/3.10.8/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 626, in _read
    return parser.read(nrows)
  File "/Users/spencerduran/.pyenv/versions/3.10.8/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1923, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
  File "/Users/spencerduran/.pyenv/versions/3.10.8/lib/python3.10/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
  File "parsers.pyx", line 838, in pandas._libs.parsers.TextReader.read_low_memory
  File "parsers.pyx", line 905, in pandas._libs.parsers.TextReader._read_rows
  File "parsers.pyx", line 874, in pandas._libs.parsers.TextReader._tokenize_rows
  File "parsers.pyx", line 891, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "parsers.pyx", line 2061, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Calling read(nbytes) on source failed. Try engine='python'.

Error in prepare_data: Error tokenizing data. C error: Calling read(nbytes) on source failed. Try engine='python'.
Traceback (most recent call last):
  File "/Users/spencerduran/Code_Repos/quant-futures-analytics-py/TheStrat/sss50_percent_stats/sss50_percent_stats.py", line 15, in prepare_data
    self.df = pd.read_csv(filepath)
  File "/Users/spencerduran/.pyenv/versions/3.10.8/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/spencerduran/.pyenv/versions/3.10.8/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 626, in _read
    return parser.read(nrows)
  File "/Users/spencerduran/.pyenv/versions/3.10.8/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1923, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
  File "/Users/spencerduran/.pyenv/versions/3.10.8/lib/python3.10/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
  File "parsers.pyx", line 838, in pandas._libs.parsers.TextReader.read_low_memory
  File "parsers.pyx", line 905, in pandas._libs.parsers.TextReader._read_rows
  File "parsers.pyx", line 874, in pandas._libs.parsers.TextReader._tokenize_rows
  File "parsers.pyx", line 891, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "parsers.pyx", line 2061, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Calling read(nbytes) on source failed. Try engine='python'.



=== Analysis for 60min Timeframe ===
Error in prepare_data: Error tokenizing data. C error: Calling read(nbytes) on source failed. Try engine='python'.
Traceback (most recent call last):
  File "/Users/spencerduran/Code_Repos/quant-futures-analytics-py/TheStrat/sss50_percent_stats/sss50_percent_stats.py", line 15, in prepare_data
    self.df = pd.read_csv(filepath)
  File "/Users/spencerduran/.pyenv/versions/3.10.8/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/spencerduran/.pyenv/versions/3.10.8/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 626, in _read
    return parser.read(nrows)
  File "/Users/spencerduran/.pyenv/versions/3.10.8/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1923, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
  File "/Users/spencerduran/.pyenv/versions/3.10.8/lib/python3.10/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
  File "parsers.pyx", line 838, in pandas._libs.parsers.TextReader.read_low_memory
  File "parsers.pyx", line 905, in pandas._libs.parsers.TextReader._read_rows
  File "parsers.pyx", line 874, in pandas._libs.parsers.TextReader._tokenize_rows
  File "parsers.pyx", line 891, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "parsers.pyx", line 2061, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Calling read(nbytes) on source failed. Try engine='python'.

Error in prepare_data: Error tokenizing data. C error: Calling read(nbytes) on source failed. Try engine='python'.
Traceback (most recent call last):
  File "/Users/spencerduran/Code_Repos/quant-futures-analytics-py/TheStrat/sss50_percent_stats/sss50_percent_stats.py", line 15, in prepare_data
    self.df = pd.read_csv(filepath)
  File "/Users/spencerduran/.pyenv/versions/3.10.8/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/spencerduran/.pyenv/versions/3.10.8/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 626, in _read
    return parser.read(nrows)
  File "/Users/spencerduran/.pyenv/versions/3.10.8/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1923, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
  File "/Users/spencerduran/.pyenv/versions/3.10.8/lib/python3.10/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
  File "parsers.pyx", line 838, in pandas._libs.parsers.TextReader.read_low_memory
  File "parsers.pyx", line 905, in pandas._libs.parsers.TextReader._read_rows
  File "parsers.pyx", line 874, in pandas._libs.parsers.TextReader._tokenize_rows
  File "parsers.pyx", line 891, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "parsers.pyx", line 2061, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Calling read(nbytes) on source failed. Try engine='python'.



=== Analysis for 30min Timeframe ===
Error in prepare_data: Error tokenizing data. C error: Calling read(nbytes) on source failed. Try engine='python'.
Traceback (most recent call last):
  File "/Users/spencerduran/Code_Repos/quant-futures-analytics-py/TheStrat/sss50_percent_stats/sss50_percent_stats.py", line 15, in prepare_data
    self.df = pd.read_csv(filepath)
  File "/Users/spencerduran/.pyenv/versions/3.10.8/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/spencerduran/.pyenv/versions/3.10.8/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 626, in _read
    return parser.read(nrows)
  File "/Users/spencerduran/.pyenv/versions/3.10.8/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1923, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
  File "/Users/spencerduran/.pyenv/versions/3.10.8/lib/python3.10/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
  File "parsers.pyx", line 838, in pandas._libs.parsers.TextReader.read_low_memory
  File "parsers.pyx", line 905, in pandas._libs.parsers.TextReader._read_rows
  File "parsers.pyx", line 874, in pandas._libs.parsers.TextReader._tokenize_rows
  File "parsers.pyx", line 891, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "parsers.pyx", line 2061, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Calling read(nbytes) on source failed. Try engine='python'.

Error in prepare_data: Error tokenizing data. C error: Calling read(nbytes) on source failed. Try engine='python'.
Traceback (most recent call last):
  File "/Users/spencerduran/Code_Repos/quant-futures-analytics-py/TheStrat/sss50_percent_stats/sss50_percent_stats.py", line 15, in prepare_data
    self.df = pd.read_csv(filepath)
  File "/Users/spencerduran/.pyenv/versions/3.10.8/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/spencerduran/.pyenv/versions/3.10.8/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 626, in _read
    return parser.read(nrows)
  File "/Users/spencerduran/.pyenv/versions/3.10.8/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1923, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
  File "/Users/spencerduran/.pyenv/versions/3.10.8/lib/python3.10/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
  File "parsers.pyx", line 838, in pandas._libs.parsers.TextReader.read_low_memory
  File "parsers.pyx", line 905, in pandas._libs.parsers.TextReader._read_rows
  File "parsers.pyx", line 874, in pandas._libs.parsers.TextReader._tokenize_rows
  File "parsers.pyx", line 891, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "parsers.pyx", line 2061, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Calling read(nbytes) on source failed. Try engine='python'.



=== Analysis for 15min Timeframe ===
Error in prepare_data: Error tokenizing data. C error: Calling read(nbytes) on source failed. Try engine='python'.
Traceback (most recent call last):
  File "/Users/spencerduran/Code_Repos/quant-futures-analytics-py/TheStrat/sss50_percent_stats/sss50_percent_stats.py", line 15, in prepare_data
    self.df = pd.read_csv(filepath)
  File "/Users/spencerduran/.pyenv/versions/3.10.8/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/spencerduran/.pyenv/versions/3.10.8/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 626, in _read
    return parser.read(nrows)
  File "/Users/spencerduran/.pyenv/versions/3.10.8/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1923, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
  File "/Users/spencerduran/.pyenv/versions/3.10.8/lib/python3.10/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
  File "parsers.pyx", line 838, in pandas._libs.parsers.TextReader.read_low_memory
  File "parsers.pyx", line 905, in pandas._libs.parsers.TextReader._read_rows
  File "parsers.pyx", line 874, in pandas._libs.parsers.TextReader._tokenize_rows
  File "parsers.pyx", line 891, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "parsers.pyx", line 2061, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Calling read(nbytes) on source failed. Try engine='python'.

Error in prepare_data: Error tokenizing data. C error: Calling read(nbytes) on source failed. Try engine='python'.
Traceback (most recent call last):
  File "/Users/spencerduran/Code_Repos/quant-futures-analytics-py/TheStrat/sss50_percent_stats/sss50_percent_stats.py", line 15, in prepare_data
    self.df = pd.read_csv(filepath)
  File "/Users/spencerduran/.pyenv/versions/3.10.8/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/spencerduran/.pyenv/versions/3.10.8/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 626, in _read
    return parser.read(nrows)
  File "/Users/spencerduran/.pyenv/versions/3.10.8/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1923, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
  File "/Users/spencerduran/.pyenv/versions/3.10.8/lib/python3.10/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
  File "parsers.pyx", line 838, in pandas._libs.parsers.TextReader.read_low_memory
  File "parsers.pyx", line 905, in pandas._libs.parsers.TextReader._read_rows
  File "parsers.pyx", line 874, in pandas._libs.parsers.TextReader._tokenize_rows
  File "parsers.pyx", line 891, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "parsers.pyx", line 2061, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Calling read(nbytes) on source failed. Try engine='python'.


Results saved to retracement_analysis_results.csv
